try:
    from .image_sender_node import NODE_CLASS_MAPPINGS as IMAGE_SENDER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_SENDER_NODE_DISPLAY_NAME_MAPPINGS
    print(f"[Base64Nodes] image_sender_node 导入成功: {list(IMAGE_SENDER_NODE_CLASS_MAPPINGS.keys())}")
except ImportError as e:
    try:
        # 备选方案：绝对导入
        from image_sender_node import NODE_CLASS_MAPPINGS as IMAGE_SENDER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_SENDER_NODE_DISPLAY_NAME_MAPPINGS
        print(f"[Base64Nodes] image_sender_node 绝对导入成功: {list(IMAGE_SENDER_NODE_CLASS_MAPPINGS.keys())}")
    except ImportError:
        print(f"[Base64Nodes] image_sender_node 导入失败: {e}")
        IMAGE_SENDER_NODE_CLASS_MAPPINGS = {}
        IMAGE_SENDER_NODE_DISPLAY_NAME_MAPPINGS = {}

try:
    from .websocket_image_sender import NODE_CLASS_MAPPINGS as WEBSOCKET_SENDER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as WEBSOCKET_SENDER_NODE_DISPLAY_NAME_MAPPINGS
    print(f"[Base64Nodes] websocket_image_sender 导入成功: {list(WEBSOCKET_SENDER_NODE_CLASS_MAPPINGS.keys())}")
except ImportError as e:
    try:
        # 备选方案：绝对导入
        from websocket_image_sender import NODE_CLASS_MAPPINGS as WEBSOCKET_SENDER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as WEBSOCKET_SENDER_NODE_DISPLAY_NAME_MAPPINGS
        print(f"[Base64Nodes] websocket_image_sender 绝对导入成功: {list(WEBSOCKET_SENDER_NODE_CLASS_MAPPINGS.keys())}")
    except ImportError:
        print(f"[Base64Nodes] websocket_image_sender 导入失败: {e}")
        WEBSOCKET_SENDER_NODE_CLASS_MAPPINGS = {}
        WEBSOCKET_SENDER_NODE_DISPLAY_NAME_MAPPINGS = {}

try:
    from .base64_nodes import NODE_CLASS_MAPPINGS as BASE64_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BASE64_NODE_DISPLAY_NAME_MAPPINGS
except ImportError:
    from base64_nodes import NODE_CLASS_MAPPINGS as BASE64_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BASE64_NODE_DISPLAY_NAME_MAPPINGS

try:
    from .image_websocket_node import NODE_CLASS_MAPPINGS as WEBSOCKET_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as WEBSOCKET_NODE_DISPLAY_NAME_MAPPINGS
except ImportError:
    from image_websocket_node import NODE_CLASS_MAPPINGS as WEBSOCKET_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as WEBSOCKET_NODE_DISPLAY_NAME_MAPPINGS

try:
    from .leafer_receiver_node import NODE_CLASS_MAPPINGS as LEAFER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LEAFER_NODE_DISPLAY_NAME_MAPPINGS
except ImportError:
    from leafer_receiver_node import NODE_CLASS_MAPPINGS as LEAFER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LEAFER_NODE_DISPLAY_NAME_MAPPINGS

try:
    from .workflow_saver_node import NODE_CLASS_MAPPINGS as WORKFLOW_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as WORKFLOW_NODE_DISPLAY_NAME_MAPPINGS
except ImportError:
    try:
        from workflow_saver_node import NODE_CLASS_MAPPINGS as WORKFLOW_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as WORKFLOW_NODE_DISPLAY_NAME_MAPPINGS
    except ImportError:
        WORKFLOW_NODE_CLASS_MAPPINGS = {}
        WORKFLOW_NODE_DISPLAY_NAME_MAPPINGS = {}

try:
    from .minimind_node import NODE_CLASS_MAPPINGS as MINIMIND_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MINIMIND_NODE_DISPLAY_NAME_MAPPINGS
except ImportError:
    try:
        from minimind_node import NODE_CLASS_MAPPINGS as MINIMIND_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MINIMIND_NODE_DISPLAY_NAME_MAPPINGS
    except ImportError:
        MINIMIND_NODE_CLASS_MAPPINGS = {}
        MINIMIND_NODE_DISPLAY_NAME_MAPPINGS = {}

try:
    from .input_nodes import NODE_CLASS_MAPPINGS as INPUT_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as INPUT_NODE_DISPLAY_NAME_MAPPINGS
except ImportError:
    from input_nodes import NODE_CLASS_MAPPINGS as INPUT_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as INPUT_NODE_DISPLAY_NAME_MAPPINGS

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {**BASE64_NODE_CLASS_MAPPINGS, **WEBSOCKET_NODE_CLASS_MAPPINGS, **LEAFER_NODE_CLASS_MAPPINGS, **WORKFLOW_NODE_CLASS_MAPPINGS, **MINIMIND_NODE_CLASS_MAPPINGS, **INPUT_NODE_CLASS_MAPPINGS, **IMAGE_SENDER_NODE_CLASS_MAPPINGS, **WEBSOCKET_SENDER_NODE_CLASS_MAPPINGS}

# 合并显示名称映射
NODE_DISPLAY_NAME_MAPPINGS = {**BASE64_NODE_DISPLAY_NAME_MAPPINGS, **WEBSOCKET_NODE_DISPLAY_NAME_MAPPINGS, **LEAFER_NODE_DISPLAY_NAME_MAPPINGS, **WORKFLOW_NODE_DISPLAY_NAME_MAPPINGS, **MINIMIND_NODE_DISPLAY_NAME_MAPPINGS, **INPUT_NODE_DISPLAY_NAME_MAPPINGS, **IMAGE_SENDER_NODE_DISPLAY_NAME_MAPPINGS, **WEBSOCKET_SENDER_NODE_DISPLAY_NAME_MAPPINGS}

# 设置Web目录以加载JavaScript扩展
WEB_DIRECTORY = "web"

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']